#!/bin/bash

while [[ $(grep -oP '^ROOTID *= *["'"'"']?([^"'"'"'\._]*)[\._]' DC-*) ]]; do
  sed -i -r 's/ROOTID *= *["'"'"']?([^"'"'"'\._]*)([\._]([^"'"'"']*))?["'"'"']?/ROOTID=\1-\3/g' DC-*
done
sed -i -r 's/^(ROOTID=[^-]+(-[^-]+)+)-+$/\1/g' DC-*

for f in xml/*.xml; do
  cat $f | tr '\n' '\r' | sed -r -e 's/\b(linkend|arearefs|xml:id|id)[\r\t ]*=[\r\t ]*(["'"'"'])/\1=\2/g' | tr '\r' '\n' > $f.0
  mv $f.0 $f
done

while [[ $(grep -oP '\b(linkend|arearefs|xml:id|id)=["'"'"']([^"'"'"'\._]*)[\._]' xml/*.xml) ]]; do
  sed -i -r 's/\b(linkend|arearefs|xml:id|id)=["'"'"']([^"'"'"'\._]*)([\._]([^"'"'"']*))?["'"'"']/\1="\2-\4"/g' xml/*.xml
done

sed -i -r 's/-+"/"/g' xml/*.xml

# remove temp files from sed
if [[ $(ls xml/sed* 2>/dev/null) ]] || [[ $(ls sed* 2>/dev/null) ]]; then
  for s in xml/sed* sed*; do
    KNOWN=`git ls-files $s | wc -l`
    if [ "$KNOWN" -ne "1" ]; then
      rm -rf $s
    fi
  done
fi
