#!/bin/bash

# Either use the default ("xml/*.xml") or the arguments passed on the command line:

me="${0##*/}"
medir=$(dirname "$0")

verbose=0

if [ "-h" = "$1" ] || [ "--help" = "$1" ]; then
  echo "$ME [-h|--help]"
  echo "$ME [-v|--verbose] [XML_FILE]..."
  exit 0
fi

if [ "-v" = "$1" ] || [ "--verbose" = "$1" ]; then
  verbose=1
  shift
fi

source=${@:-xml/*.xml}

for f in $source; do
  [[ "$verbose" = 1 ]] && echo "- terms/titles in [ $f ]"
  ttl=$(grep -Pn '<(title|term)>' "$f")
  len=$(echo -e "$ttl" | wc -l)
  [[ "$ttl" == "" ]] && continue
  for i in $(seq 1 ${len}); do
    ful=$(echo -e "$ttl" | sed -n "$i p")
    num=$(echo "$ful" | grep -Po '^[0-9]+')
    lin=$(echo "$ful" | sed -r 's/^[0-9]+://')
    pre=$(echo "$lin" | grep -Po '^.*<(title|term)>')
    pos=$(echo "$lin" | grep -Po '</(title|term)>.*$')
    met=$(echo "$lin" | sed -r -e 's_^.*<(title|term)>__' -e 's_</(title|term)>.*$__')
    unp="$met"
    ini=1
    pro=""
    [[ "$verbose" = 1 ]] && echo "${num} -| ${unp}"
    while [[ "$unp" ]]; do
     # self-closing tags
     if [[ $(echo "$unp" | grep -Po "^<[^ >]+ *([^= >]+=['"'"'"][^'"'"'"]*['"'"'"])* */>") ]]; then
       wor=$(echo "$unp" | grep -Po "^<[^ >]+ *([^= >]+=['"'"'"][^'"'"'"]*['"'"'"])* */>")
       unp=$(echo "$unp" | sed -r "s_^<[^ >]+ *([^= >]+=['"'"'"][^'"'"'"]*['"'"'"])* */>__")
       pro+="$wor"
       continue
     # normal tags
     elif [[ $(echo "$unp" | grep "^<") ]]; then
       wor=$(echo "$unp" | grep -Po '^<[^>]+>[^<]+<[^>]+>')
       unp=$(echo "$unp" | sed -r 's_^<[^>]+>[^<]+<[^>]+>__')
       pro+="$wor"
       continue
     #entities
     elif [[ $(echo "$unp" | grep "^\&") ]]; then
       wor=$(echo "$unp" | grep -Po '^\&[^;];')
       unp=$(echo "$unp" | sed -r 's_^\&[^;];__')
       pro+="$wor"
       continue
     else
       wor=$(echo "$unp" | grep -Po '^[^ <;(/-]*.')
       unp=$(echo "$unp" | sed -r 's_^[^ <;(/-]*.__')
     fi
     # never change the first word
     if [[ $ini -eq 1 ]]; then
       pro+="$wor"
     # never change acronyms, which we assume are characterized by at least two leading capitals
     elif [[ $(echo "$wor" | grep "^[A-Z][A-Z]" ) ]]; then
       pro+="$wor"
     # never change the words from the list
     # -F fixed-strings, no regex support; -w word-based; -f load strings from file
     elif [[ $(echo "$wor" | grep -Fw -f "$medir/keep-case-list" ) ]]; then
       pro+="$wor"
     # -> change these things
     elif [[ $(echo "$wor" | grep "^[A-Z]" ) ]]; then
       pro+=$(echo -n "$wor" | sed -r 's/(.)(.*)/\L\1\E\2/')
     # never change anything else
     else
       pro+="$wor"
     fi
     ini=0
    done
    [[ "$verbose" = 1 ]] && echo -e "${num} +| ${pro}\n"
    rea=$(echo "${pre}${pro}${pos}" | sed -e 's_/_\\/_g' -e 's_\&_\\\&_g' )
    sed -i "${num}"' s/.*/'"$rea"'/' "$f"
  done
  [[ "$verbose" = 1 ]] && echo -e "----\n"
done
